swagger: "2.0"
info:
  version: "0.0.1"
  title: Dominioneer

# during dev, should point to your local machine
host: dominioneer.elasticbeanstalk.com
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
securityDefinitions:
  rating_auth:
    type: oauth2
    authorizationUrl: https://graph.facebook.com/oauth/authorize
    flow: implicit
    scopes:
      public_profile: the user id for a rating
  
paths:
  /randGame:
    x-swagger-router-controller: game_controller
    get:
      description: Gets a game for the given specifications
      operationId: randGame
      parameters:
        - name: cards
          in: query
          description: the cards that are required to be in the chosen game
          required: false
          type: array
          items: 
            type: string
          collectionFormat: csv
        - name: sets
          in: query
          description: the different dominion expansions that are available
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Game"
        "400":
          description: game was requested with invalid parameters
          schema:
            $ref: "#/definitions/Error"
  /games:
    x-swagger-router-controller: game_controller
    get:
      description: Gets a game for the given specifications
      operationId: generateGame
      parameters:
        - name: players
          in: query
          description: the players that are playing in the game
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: sets
          in: query
          description: the different dominion expansions that are available
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Game"
        "400":
          description: game was requested with invalid parameters
          schema:
            $ref: "#/definitions/Error"
      security: 
        - rating_auth:
          - public_profile
            
  /games/{gameId}:
    x-swagger-router-controller: game_controller
    get:
      description: Gets the information about a specific game
      operationId: getGame
      parameters:
        - name: gameId
          in: path
          type: string
          description: the identifier of the game
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Game"
            
    put:
      description: Puts an unrated game in the user history, indicating it has been played, but not rated.  Will also put the game in the other players history.
      operationId: playGame
      parameters:
        - name: gameId
          in: path
          type: string
          description: the identifier of the game
        - name: players
          in: query
          description: the players that are playing in the game
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Game"
        "400":
          description: game was requested with invalid parameters
          schema:
            $ref: "#/definitions/Error"
      security: 
        - rating_auth:
          - public_profile
        
  /games/{gameId}/prediction:
    x-swagger-router-controller: user_controller
    get:
      description: gets a prediction for how much a user will like a game (between 0 and 1)
      operationId: predict
      parameters:
        - name: gameId
          in: path
          type: string
          description: the id of a game to rate
      responses:
        "200":
          description: a successful prediction has been made
          schema:
            $ref: "#/definitions/Rating"
      security: 
        - rating_auth:
          - public_profile
  
  /ratings:
    x-swagger-router-controller: ratings_controller
    get:
      description: gets all the ratings for the user
      operationId: getRatings
      responses:
        "200":
          description: successful operation
          schema:
            type: array
            items:
              $ref: "#/definitions/Rating"
      security: 
        - rating_auth:
          - public_profile
      
  /ratings/{gameId}:
    x-swagger-router-controller: ratings_controller
    get:
      description: gets the rating for the user and the game
      operationId: getRating
      parameters:
        - name: gameId
          in: path
          type: string
          description: the id of a game to rate
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Rating"      
      security: 
        - rating_auth:
          - public_profile

  /ratings/{gameId}/rating/{rating}:
    x-swagger-router-controller: ratings_controller
    put:
      description: rates a game for a particular user
      operationId: addRating
      parameters:
        - name: gameId
          in: path
          type: string
          description: the id of a game to rate 
        - name: rating
          in: path
          type: number
          description: the rating the player has given the game
      responses:
        "200":
          description: successful operation
          schema:
            $ref: "#/definitions/Rating"      
      security: 
        - rating_auth:
          - public_profile
          
# complex objects have schema definitions
definitions:
  Game:
    required:
      - id
    properties:
      id:
        type: string
      rating:
        type: number
      cards:
        type: array
        items:
          $ref: "#/definitions/Card"
  Card:
    required:
      - name
    properties:
      name:
        type: string
      cardtype:
        type: string
      price:
        type: string
        
  Rating:
    properties:
      gameId:
        type: string
      userId:
        type: string
      rating:
        type: number
        
  Error:
    properties:
      message:
        type: string